In [247]:
import pandas as pd

In [248]:
df = pd.read_csv("filmler_clean.csv")

In [249]:
df.head()

film adi  \
0                                       Bergen   
1                                Kirpi Sonic 2   
2  Fantastik Canavarlar: Dumbledore'un Sırları   
3                               Aykut Enişte 2   
4                                      Morbius   

                                    ozet ve detaylar  \
0  Arabeskin unutulmayan kadın seslerinden biri o...   
1  Çocuk filmi \r\n\r\n\r\nKirpi Sonic filminin d...   
2  Karanlık büyücü Gellert Grindelwald, büyücülük...   
3  Aykut Enişte 2, sevdiği kadınla evlilik arifes...   
4  Morbius, hastalığına deva bulmaya çalışırken b...   

                                  tur  \
0              ['Dram', 'Biyografik']   
1     ['Animasyon', 'Aile', 'Macera']   
2             ['Fantastik', 'Macera']   
3                          ['Komedi']   
4  ['Aksiyon', 'Fantastik', 'Macera']   

                                           oyuncular  \
0  ['Farah Zeynep Abdullah', 'Erdal Beşikçioğlu',...   
1              ['Jim Carrey', 'James Marsden', None]   
2   ['Eddie Redmayne', 'Jude Law', 'Mads Mikkelsen']   
3  ['Cem Gelinoğlu', 'Melis Babadağ', 'Hakan Yılm...   
4  ['Jared Leto', 'Matt Smith (XI)', 'Adria Arjona']   

                          yonetmen  vizyon tarihi     sure  \
0  ['Mehmet Binay', 'Caner Alper']    4 Mart 2022  2s 26dk   
1                  ['Jeff Fowler']   8 Nisan 2022   2s 2dk   
2                  ['David Yates']  15 Nisan 2022  2s 22dk   
3                ['Onur Bilgetay']  3 Aralık 2021  1s 55dk   
4              ['Daniel Espinosa']   1 Nisan 2022  1s 45dk   

                                               clean  
0  arabesk unutmak kadın ses o Bergen inmek hayat...  
1  çocuk film kirpi Sonic film deva halka o yapım...  
2  Karanlık büyü Gellert Grindelwald büyü Dünya k...  
3  Aykut enişte 2 sevmek kadın ev arife kendi tür...  
4  Morbius hastalık deva bulmak Çalışır bambaşka ...

In [250]:
clean = df["clean"]

In [251]:
len(clean)

5261

In [252]:
word2idx = {}
idx2word = {}

In [253]:
i = 0
for cell in clean:
    words = cell.split()
    for word in words:
        if word in word2idx:
            continue
        word2idx[word] = i
        idx2word[i] = word
        i += 1

In [254]:
print(len(word2idx))


27754


In [255]:
import numpy as np

In [256]:
film_sayisi = len(clean)
vocab_size = len(word2idx)


In [257]:
filmler = np.zeros((film_sayisi, vocab_size))


In [258]:
filmler.shape

(5261, 27754)

In [259]:
turler_list =df["tur"]
oyuncular_list = df["oyuncular"]
yonetmen_list = df["yonetmen"]

# tuler,yonetmenler ve oyunculari da islemlere katmak icin once tanitiyoruz.

In [260]:
turler2idx = {}
idx2tur = {}
clean_turler = []
k = 0

for i,turler in enumerate(turler_list):
    clean_turler.append(turler.strip("[]").replace("'","").split(", "))
    # liste halinde gozukse de string'ti ve [] isareti vardi. kaldirildi.
    # ' isareti kaldirildi string'te bulunuyordu.
    # virgul ve sonrasinda gelen bosluk silindi ve liste haline donusturuldu.

for i,turler in enumerate(clean_turler):
    for tur in turler:
        if tur in turler2idx:
            continue
        turler2idx[tur] = k
        idx2tur[k] = tur 
        k = k+1

In [261]:
oyuncular2idx = {}
idx2oyuncu = {}
clean_oyuncular = []
k = 0

for i,oyuncular in enumerate(oyuncular_list):
    clean_oyuncu = oyuncular.strip("[]").replace("'","").split(", ")
    clean_oyuncular.append(clean_oyuncu)
    # liste halinde gozukse de string'ti ve [] isareti vardi. kaldirildi.
    # ' isareti kaldirildi string'te bulunuyordu.
    # virgul ve sonrasinda gelen bosluga bagli olarak liste haline donusturuldu.

for i,oyuncular in enumerate(clean_oyuncular):
    for oyuncu in oyuncular:
        if oyuncu in oyuncular2idx:
            # oyuncularin birden fazla islenmesini engellemek icin.
            continue
        oyuncular2idx[oyuncu] = k;
        idx2oyuncu[k] = oyuncu
        k += 1

In [262]:
yonetmenler2idx = {}
idx2yonetmen = {}
clean_yonetmenler = []
k = 0

for i,yonetmenler in enumerate(yonetmen_list):
    clean_yonetmen = yonetmenler.strip("[]").replace("'","").split(", ")
    clean_yonetmenler.append(clean_yonetmen) 
    # liste halinde gozukse de string'ti ve [] isareti vardi. kaldirildi.
    # ' isareti kaldirildi string'te bulunuyordu.
    # virgul ve sonrasinda gelen bosluk silindi ve liste haline donusturuldu.

for i,yonetmenler in enumerate(clean_yonetmenler):
    for yonetmen in yonetmenler:
        if yonetmen in yonetmenler2idx:
            # yonetmenlerin birden fazla islenmesini engellemek icin.
            continue
        yonetmenler2idx[yonetmen] = k;
        idx2yonetmen[k] = yonetmen       
        k += 1

In [263]:
tur_size = len(turler2idx)
oyuncu_size = len(oyuncular2idx)
yonetmen_size = len(yonetmenler2idx)

In [264]:
turler_matrix = np.zeros((film_sayisi, tur_size))
oyuncular_matrix = np.zeros((film_sayisi, oyuncu_size))
yonetmenler_matrix = np.zeros((film_sayisi, yonetmen_size))

In [266]:
print(len(turler2idx))
print(len(oyuncular2idx))
print(len(yonetmenler2idx))

31
6231
2539


In [267]:
for i, cell in enumerate(clean):
    words = cell.split()
    for word in words:
        wordIndex = word2idx[word]
        filmler[i][wordIndex] += 1


In [268]:
for i, words in enumerate(clean_turler):
    for word in words:
        wordIndex = turler2idx[word]
        turler_matrix[i][wordIndex] += 1

In [269]:
for i, words in enumerate(clean_oyuncular):
    for word in words:
        wordIndex = oyuncular2idx[word]
        if not word == "None": oyuncular_matrix[i][wordIndex] +=1
        # 'NONE' kelimesini iceriyor ise degeri arttirma.

In [270]:
for i, words in enumerate(clean_yonetmenler):
    for word in words:
        wordIndex = yonetmenler2idx[word]
        yonetmenler_matrix[i][wordIndex] += 1
        

In [271]:
yonetmenler_matrix

array([[1., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [272]:
filmler[7][:10]

array([0., 0., 0., 0., 2., 0., 1., 2., 0., 0.])

In [273]:
turler_matrix[0]

array([1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [274]:
doc_frequencies = {}
# 1 - 5 dk sürebilir 
for word in word2idx:
    doc_count = 0
    for film in clean:
        if word in film:
            doc_count += 1
    
    doc_frequencies[word] = doc_count


In [275]:
tur_frequencies = {}

for word in turler2idx:
    tur_count = 0
    for turler in clean_turler:
        if word in turler:
            tur_count += 1

    tur_frequencies[word] = tur_count

In [276]:
oyuncu_frequencies = {}

for word in oyuncular2idx:
    oyuncu_count = 0
    if word == "None":oyuncu_frequencies[word] = oyuncu_count
    # Verilerimizde oyunculardan bazilari 'NONE' iceriyordu bu yuzden 'NONE' 
    # kelimesini gordugu yere 0 yazdirdim.'NONE' gormezden gelindi.
    for oyuncular in clean_oyuncular:
        if word in oyuncular:
            oyuncu_count += 1
    oyuncu_frequencies[word] = oyuncu_count

In [277]:
yonetmen_frequencies = {}

for word in yonetmenler2idx:
    yonetmen_count = 0
    for yonetmenler in clean_yonetmenler:
        if word in yonetmenler:
            yonetmen_count += 1
    yonetmen_frequencies[word] = yonetmen_count

In [278]:
sorted_frequencies = sorted(doc_frequencies, key=doc_frequencies.get, reverse=True)
sorted_tur_frequencies = sorted(tur_frequencies, key=tur_frequencies.get, reverse=True)
sorted_oyuncu_frequencies = sorted(oyuncu_frequencies, key=oyuncu_frequencies.get, reverse=True)
sorted_yonetmen_frequencies = sorted(yonetmen_frequencies, key=yonetmen_frequencies.get, reverse=True)

In [282]:
# 1 - 5 dk sürebilir
filmler_tf_idf = np.zeros((film_sayisi, vocab_size))
film_sayisi = len(clean)

for i, film in enumerate(filmler):
    if i % 500 == 0:
        print(f"{film_sayisi} filmden {i}. film işleniyor...")
    for j, tf in enumerate(film):
        idf = 0
        if tf > 0:
            idf = np.log(film_sayisi / (doc_frequencies[idx2word[j]] + 1)) + 1

        tf_idf_score = tf * idf 
        filmler_tf_idf[i][j] = tf_idf_score

5261 filmden 0. film işleniyor...
5261 filmden 500. film işleniyor...
5261 filmden 1000. film işleniyor...
5261 filmden 1500. film işleniyor...
5261 filmden 2000. film işleniyor...
5261 filmden 2500. film işleniyor...
5261 filmden 3000. film işleniyor...
5261 filmden 3500. film işleniyor...
5261 filmden 4000. film işleniyor...
5261 filmden 4500. film işleniyor...
5261 filmden 5000. film işleniyor...


In [283]:
turler_tf_idf = np.zeros((film_sayisi, tur_size))

for i, tur in enumerate(turler_matrix):
    if i % 500 == 0:
        print(f"{len(turler_matrix)} turden {i}. tur işleniyor...")
    for j, tf in enumerate(tur):
        idf = 0;
        if tf > 0:
            idf =  np.log(film_sayisi / (tur_frequencies[idx2tur[j]] + 1)) + 1
        
        tf_idf_score = (tf * idf)
        turler_tf_idf[i][j] = tf_idf_score

5261 turden 0. tur işleniyor...
5261 turden 500. tur işleniyor...
5261 turden 1000. tur işleniyor...
5261 turden 1500. tur işleniyor...
5261 turden 2000. tur işleniyor...
5261 turden 2500. tur işleniyor...
5261 turden 3000. tur işleniyor...
5261 turden 3500. tur işleniyor...
5261 turden 4000. tur işleniyor...
5261 turden 4500. tur işleniyor...
5261 turden 5000. tur işleniyor...


In [284]:
oyuncular_tf_idf = np.zeros((film_sayisi, oyuncu_size))

for i, oyuncu in enumerate(oyuncular_matrix):
    if i % 500 == 0:
        print(f"{len(oyuncular_matrix)} turden {i}. tur işleniyor...")
    for j, tf in enumerate(oyuncu):
        idf = 0;
        if tf > 0:
            idf =  np.log(film_sayisi / (oyuncu_frequencies[idx2oyuncu[j]] + 1)) + 1
        
        tf_idf_score = (tf * idf)
        oyuncular_tf_idf[i][j] = tf_idf_score

5261 turden 0. tur işleniyor...
5261 turden 500. tur işleniyor...
5261 turden 1000. tur işleniyor...
5261 turden 1500. tur işleniyor...
5261 turden 2000. tur işleniyor...
5261 turden 2500. tur işleniyor...
5261 turden 3000. tur işleniyor...
5261 turden 3500. tur işleniyor...
5261 turden 4000. tur işleniyor...
5261 turden 4500. tur işleniyor...
5261 turden 5000. tur işleniyor...


In [285]:
yonetmenler_tf_idf = np.zeros((film_sayisi, yonetmen_size))

for i, yonetmen in enumerate(yonetmenler_matrix):
    if i % 500 == 0:
        print(f"{len(yonetmenler_matrix)} turden {i}. tur işleniyor...")
    for j, tf in enumerate(yonetmen):
        idf = 0;
        if tf > 0:
            idf =  np.log(film_sayisi / (yonetmen_frequencies[idx2yonetmen[j]] + 1)) + 1
        
        tf_idf_score = (tf * idf)
        yonetmenler_tf_idf[i][j] = tf_idf_score

5261 turden 0. tur işleniyor...
5261 turden 500. tur işleniyor...
5261 turden 1000. tur işleniyor...
5261 turden 1500. tur işleniyor...
5261 turden 2000. tur işleniyor...
5261 turden 2500. tur işleniyor...
5261 turden 3000. tur işleniyor...
5261 turden 3500. tur işleniyor...
5261 turden 4000. tur işleniyor...
5261 turden 4500. tur işleniyor...
5261 turden 5000. tur işleniyor...


In [286]:
print(filmler_tf_idf[1][:10])
print(filmler[1][:10])

[0.         0.         0.         0.         2.00038019 0.
 7.50567832 0.         0.         2.87073982]
[0. 0. 0. 0. 2. 0. 4. 0. 0. 2.]


In [287]:
print(turler_tf_idf[1][:10])
print(turler_matrix[1][:10])
print(oyuncular_matrix[1][:10])

[0.         0.         3.75993391 3.9226295  3.11287784 0.
 0.         0.         0.         0.        ]
[0. 0. 1. 1. 1. 0. 0. 0. 0. 0.]
[0. 0. 0. 1. 1. 0. 0. 0. 0. 0.]


In [288]:
def cos_sim(v1, v2):
    return np.dot(v1, v2) / ((np.linalg.norm(v1) * np.linalg.norm(v2)+1))

In [289]:
def film_2_str(row_index):
    film = df.iloc[row_index]
    adi = film['film adi']
    turu = film['tur']
    oyunculari = film['oyuncular']
    yonetmenleri = film['yonetmen']
    ozet = film['ozet ve detaylar']
    if len(ozet) > 150:
        ozet = ozet[:150] + "..."

    return f"Film adı: {adi} \nTürü: {turu} \nOyuncular: {oyunculari}\nYonetmenleri: {yonetmenleri} \nÖzeti: {ozet}"

In [290]:
print(film_2_str(0))

Film adı: Bergen 
Türü: ['Dram', 'Biyografik'] 
Oyuncular: ['Farah Zeynep Abdullah', 'Erdal Beşikçioğlu', 'Tilbe Saran']
Yonetmenleri: ['Mehmet Binay', 'Caner Alper'] 
Özeti: Arabeskin unutulmayan kadın seslerinden biri olan Bergen'in hayatını anlatan filmde, Bergen olarak bilinen Belgin'in Ankara'dan Adana'ya, oradan da ya...


In [291]:
def most_similar_films(film_adi, benzer_film_sayisi):
    film_indexi = df[df["film adi"] == film_adi].index[0]
    print("Aranan Film:")
    print(film_2_str(film_indexi))
    print()
    print("* " * 30)
    print()

    benzerlikler = []
    sorgu_film = filmler_tf_idf[film_indexi]
    sorgu_tur = turler_tf_idf[film_indexi]
    sorgu_yonetmen = yonetmenler_tf_idf[film_indexi]
    sorgu_oyuncu = oyuncular_tf_idf[film_indexi]

    for i in range(0, film_sayisi):
        vec1 = filmler_tf_idf[i]
        vec2 = turler_tf_idf[i]
        vec3 = yonetmenler_tf_idf[i]
        vec4 = oyuncular_tf_idf[i]

        benzerlik_part1 = 4 * cos_sim(sorgu_film, vec1)
        benzerlik_part2 = 6 * cos_sim(sorgu_tur, vec2)
        benzerlik_part3 = 2 * cos_sim(sorgu_yonetmen, vec3)
        benzerlik_part4 = 1 * cos_sim(sorgu_oyuncu, vec4)
        # cos0'dan cikan sonuclari agirliklarina gore carptim boylece 
        # daha benzer turler agirliklarina gore bulunmus oldu.

        benzerlik = benzerlik_part1 + benzerlik_part2 + benzerlik_part3 + benzerlik_part4
        benzerlikler.append(benzerlik)

    en_benzer_film_indexleri = (- np.array(benzerlikler)).argsort()[:benzer_film_sayisi + 1]
    print("Benzer Filmler:\n")
    for i, film_idx in enumerate(en_benzer_film_indexleri[1:]):
        print(str(i+1) + ") " + film_2_str(film_idx))
        print()
        print("- " * 20)
        print()
    

In [292]:
most_similar_films("Kirpi Sonic 2", 20)

Aranan Film:
Film adı: Kirpi Sonic 2 
Türü: ['Animasyon', 'Aile', 'Macera'] 
Oyuncular: ['Jim Carrey', 'James Marsden', None]
Yonetmenleri: ['Jeff Fowler'] 
Özeti: Çocuk filmi 


Kirpi Sonic filminin devam halkası olan yapımda, insan biçiminde bir kirpi olan Sonic'in atıldığı maceralar konu ediliyor. Green Hil...

* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * 

Benzer Filmler:

1) Film adı: Kirpi Sonic 
Türü: ['Macera', 'Aile'] 
Oyuncular: ['Jim Carrey', None, 'James Marsden']
Yonetmenleri: ['Jeff Fowler'] 
Özeti: 6 yaş ve üzeri çocuklar için uygun film



Kirpi Sonic, peşine düşen yetkililerden kurtulup, şeytani doktorun elinde bulunan yüzükleri geri almaya...

- - - - - - - - - - - - - - - - - - - - 

2) Film adı: İnanılmaz Aile 2 
Türü: ['Animasyon', 'Aile', 'Macera'] 
Oyuncular: [None, None, None]
Yonetmenleri: ['Brad Bird'] 
Özeti: Çocuk filmi 


İnanılmaz Aile 2, süper güçlere sahip olan bir ailenin atıldığı maceraları konu ediyor. Süper güçlere sahip aile suçla sav